.PHONY: build deploy clean

build:
	GOOS=linux GOARCH=amd64 go build -o ./auth-service/bootstrap ./auth-service/cmd/main.go  
	GOOS=linux GOARCH=amd64 go build -o ./email-service/bootstrap ./email-service/cmd/main.go  

deploy:
	cd deploy && cdk deploy

deploy-swap:
	cd deploy && cdk deploy --hotswap

clean:
	rm -rf ./auth-service/bootstrap
	rm -rf ./email-service/bootstrap